pipeline {
    agent any

    stages {
        stage('Build & Deploy') {
            steps {
                sh 'ls'
                sh 'docker-compose up -d'
            }
        }

        stage('Finish') {
            steps {
                sh 'echo "部署成功"了'
            }
        }
    }
}
