pipeline {

    agent any

    environment {
        PROJECT_NAME = "greedy_snake_front"
        IMAGE_NAME = "${PROJECT_NAME}:${env.BUILD_NUMBER}"
    }

    stages {
        stage('打印环境变量'){
            steps{
                echo "${PROJECT_NAME}"
                echo "${IMAGE_NAME}"
            }
        }

        stage('构建和发布Docker镜像') {
            steps {
                sh 'docker version'

                script {
                    sh "docker build -t ${IMAGE_NAME} -f ./deploy/Dockerfile ."
//                     sh """
//                         echo 'push到本地镜像仓库里面'
//                         docker tag ${dockerImageName} localhost:30500/${dockerImageName}
//                         docker push localhost:30500/${dockerImageName}
//                     """
                }
            }
        }

        stage('动态修改k8s配置文件') {
            steps {
                script {
                    sh """
                        echo '更新k3s.yaml中的项目名称和镜像名称'
                        sed -i "s/{PROJECT_NAME}/${PROJECT_NAME}/" deploy/k8s.yml
                        sed -i "s/{IMAGE_NAME}/${IMAGE_NAME}/" deploy/k8s.yml
                        cat deploy/k8s.yml
                    """
                }
            }
        }

        stage('部署k8s') {
            steps {
                sh """
                   kubectl apply -f deployment.yml
                   kubectl rollout status deployment/kalpa-home
                   """
            }
        }
    }

    post {
        always {
            cleanWs()
//             sh ''' docker rmi -f $(docker images -q)  '''
        }
    }

}