pipeline {
    agent any

    stages {
        stage('Build & Deploy') {
            steps {
                sh 'ls'
                sh 'docker-compose -f deploy/docker-compose.yml up -d  --no-cache'
            }
        }

        stage('Finish') {
            steps {
                sh 'echo "部署成功"了'
            }
        }
    }
}
