apiVersion: apps/v1
kind: Deployment
metadata:
  name: {PROJECT_NAME}
  labels:
    app: {PROJECT_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {PROJECT_NAME}
  template:
    metadata:
      labels:
        app: {PROJECT_NAME}
    spec:
      containers:
        - name: {PROJECT_NAME}
          #         这里的镜像会被jenkins 使用sed -i 命令自动替换
          image: {IMAGE_NAME}
          ports:
            - containerPort: 80
          env:
            - name: JAVA_OPTS
              value: "-Xmx512m -Xms512m"
---
apiVersion: v1
kind: Service
metadata:
  name: {PROJECT_NAME}
spec:
  selector:
    app: {PROJECT_NAME}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP